# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf050b2b83646a796cac63fc113c8e50692384a84b022b9e7b5bbc6fedde00004f75d8795af854436dfbadaea0980edeed70540ae26e5e793630f7f41941bbd

test:
  secret_key_base: 4561becd805ed49bab15aba2e30bd0623c5a04c5d096b9ace3c23dd79c2de4b830607cd905dc816fbdc98557d1374d7f3369e9d613b361b2a59d40fc3fb914d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
